FROM  nvidia/cuda:12.1.0-runtime-ubuntu20.04
LABEL MAINTAINER="chatGLM"

COPY . /chatGLM/

WORKDIR /chatGLM

RUN apt-get update -y && apt-get install python3 python3-pip curl -y  && apt-get clean
RUN python3 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn --upgrade pip

RUN pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn && rm -rf `pip3 cache dir`

CMD ["python3","-u", "webui.py"]
